import type { ArchiveRequestsService } from './archiveRequests';
import type { DashboardService } from './dashboard';
import type { IngestionCapabilitiesService } from './ingestionCapabilities';
import type { IngestionDetailService } from './ingestionDetail';
import type { IngestionOverviewService } from './ingestionOverview';
import type { IngestionNewService } from './ingestionNew';
import type { IngestionSetupService } from './ingestionSetup';
import type { ObjectEditService } from './objectEdit';
import type { ObjectsService } from './objects';
import { apiArchiveRequestsService } from './apiArchiveRequestsService';
import { apiIngestionCapabilitiesService } from './apiIngestionCapabilitiesService';
import { apiIngestionDetailService } from './apiIngestionDetailService';
import { apiDashboardService } from './apiDashboardService';
import { apiIngestionNewService } from './apiIngestionNewService';
import { apiIngestionOverviewService } from './apiIngestionOverviewService';
import { apiIngestionSetupService } from './apiIngestionSetupService';
import { apiObjectEditService } from './apiObjectEditService';
import { apiObjectsService } from './apiObjectsService';

export const archiveRequestsService: ArchiveRequestsService = apiArchiveRequestsService;
export const dashboardService: DashboardService = apiDashboardService;
export const ingestionCapabilitiesService: IngestionCapabilitiesService = apiIngestionCapabilitiesService;
export const ingestionDetailService: IngestionDetailService = apiIngestionDetailService;
export const ingestionOverviewService: IngestionOverviewService = apiIngestionOverviewService;
export const ingestionNewService: IngestionNewService = apiIngestionNewService;
export const ingestionSetupService: IngestionSetupService = apiIngestionSetupService;
export const objectEditService: ObjectEditService = apiObjectEditService;
export const objectsService: ObjectsService = apiObjectsService;
